name = "admin-dashboard"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "card-kingdom"
database_id = "5f6b3667-693b-4dca-8e92-5503d40d74c4"
